from playwright.sync_api import sync_playwright

class BasePom:
    """Base class for all generated page object models.
    
    Subclasses are auto-generated by `pom generate`. Each inner class
    represents a page with typed Locator attributes and an optional path
    for auto navigation.
    
    Usage:
    ```python
        with MySite() as site:
            site.login.username.fill("chidi@gmail.com")
    ```
    """
    
    _base_url: str = ""       # set by generated subclass

    def __init__(self, headless=False):
        # headless=False shows the browser window, useful for debugging
        self._headless = headless 
    
    def __enter__(self):
        """Start Playwright, launch browser, and bind locators."""
        self._playwright = sync_playwright().start()
        self._browser = self._playwright.chromium.launch(headless=self._headless)
        self._page = self._browser.new_page()
        if not self._base_url.strip():
            raise Exception(f"Invalid base url: {self._base_url}")
        self._page.goto(self._base_url)
        self._bind_locators()
        return self
    
    def __exit__(self, *args):
        """Close browser and stop Playwright cleanly on exit."""
        self._browser.close()
        self._playwright.stop()
    
    @property
    def page(self):
        """Expose the raw Playwright Page for advanced usage."""
        return self._page
    
    def _bind_locators(self):
        """Go through inner page classes and replace selector strings with NavLocators.
        
        Each key in _selectors becomes a NavLocator that auto-navigates
        to the page's _path before performing any Playwright action.
        """
        for section_name in dir(self.__class__):
            if section_name.startswith('_'):
                continue
            
            section = getattr(self.__class__, section_name)
            if isinstance(section, type):  # only process inner classes
                selectors = getattr(section, '_selectors', {})
                
                for attr_name, selector in selectors.items():
                    locator = self._make_locator(selector)
                    setattr(section, attr_name, locator)
    
    def _make_locator(self, selector):
        """Create a NavLocator that navigates to path before any Playwright action.
        
        Navigation only happens if the current path differs from the target path,
        avoiding redundant page loads within the same page section.
        """
        pom = self
        
        class NavLocator:
            def __getattr__(self, name):
                return getattr(pom._page.locator(selector), name)
        
        return NavLocator()